class ProxyManager {
	public static player: PlayerProxy;
	public static test: TestProxy;
	public static pack: PackProxy;
	public static refine: RefineProxy;
	public static sysSet: SysSetProxy;
	public static task: TaskProxy;
	public static ancientEquip:AncientEquipProxy;
	public static copy: CopyProxy;
	public static towerTurnable:TowerTurntableProxy;
	public static operation: OperationProxy;
	public static fashion: FashionProxy;
	public static home: HomeProxy;
	public static shop: ShopProxy;
	public static boss: BossProxy;
	public static cheats:SkillCheatsProxy;
	public static createRole: CreateRoleProxy;
	public static guild: GuildProxy;
	public static chat: ChatProxy;
	public static rune: RuneProxy;
	public static mail: MailProxy;
	public static team: TeamProxy;
	public static daily: DailyProxy;
	public static achievement:AchievementProxy;
	public static compose:ComposeProxy;
	public static godWing:GodWingProxy;
	public static title:TitleProxy;
	public static welfare: WelfareProxy;
	public static rank:RankProxy;
	public static sevenDay:SevenDayProxy;
	public static bibleActivity: BibleActivityProxy;
	public static vipGift: VipGiftProxy;
	public static forge: ForgeProxy;
	public static reincarnation:ReincarnationProxy;
	public static godEquip: GodEquipProxy;
	public static train:TrainProxy;
	public static arena:ArenaProxy;
	public static cultivate: CultivateProxy;
	public static uniqueSkill: UniqueSkillProxy;
	public static recharge:RechargeProxy;
	public static lottery:LotteryProxy;
	public static activity:ActivityProxy;
	public static welfare2: Welfare2Proxy;
	public static timeLimitTask: TimeLimitTaskProxy;
	public static fashionPlayer: FashionPlayerProxy;
	public static gamePlay:GamePlayProxy;
	public static sevenDayMagicWeapon: SevenDayMagicWeaponProxy;
	public static friend: FriendProxy;
	public static guildBattle:GuildBattleProxy;
	public static cross:CrossProxy;
	public static magicweaponstrengthen: MagicWeaponStrengthenProxy;
	public static shape: ShapeProxy;
	public static peak: PeakProxy;
	public static certification : CertificationProxy;
	public static team2 : Team2Proxy;
	public static exam: ExamProxy;
	public static beastBattle: BeastBattleProxy;
	public static contest: ContestProxy;
	public static qualifying: QualifyingProxy;

	public static init(): void {
		ProxyManager.player = new PlayerProxy();
		ProxyManager.test = new TestProxy();
		ProxyManager.pack = new PackProxy();
		ProxyManager.refine = new RefineProxy();
		ProxyManager.sysSet = new SysSetProxy();
		ProxyManager.task = new TaskProxy();
		ProxyManager.ancientEquip = new AncientEquipProxy();
		ProxyManager.copy = new CopyProxy();
		ProxyManager.towerTurnable = new TowerTurntableProxy();
		ProxyManager.operation = new OperationProxy();
		ProxyManager.fashion = new FashionProxy();
		ProxyManager.home = new HomeProxy();
		ProxyManager.shop = new ShopProxy();
		ProxyManager.boss = new BossProxy();
		ProxyManager.cheats = new SkillCheatsProxy();
		if (!ProxyManager.createRole) {
			ProxyManager.createRole= new CreateRoleProxy();
		}
		// ProxyManager.createRole = new CreateRoleProxy();
		ProxyManager.guild = new GuildProxy();
		ProxyManager.chat = new ChatProxy();
		ProxyManager.rune = new RuneProxy();
		ProxyManager.mail = new MailProxy();
		ProxyManager.team = new TeamProxy();
		ProxyManager.daily = new DailyProxy();
		ProxyManager.achievement = new AchievementProxy();
		ProxyManager.compose = new ComposeProxy();
		ProxyManager.godWing = new GodWingProxy();
		ProxyManager.title = new TitleProxy();
		ProxyManager.welfare = new WelfareProxy();
		ProxyManager.rank = new RankProxy();
		ProxyManager.sevenDay = new SevenDayProxy();
		ProxyManager.bibleActivity = new BibleActivityProxy();
		ProxyManager.vipGift = new VipGiftProxy();
		ProxyManager.forge = new ForgeProxy();
		ProxyManager.reincarnation = new ReincarnationProxy();
		ProxyManager.godEquip = new GodEquipProxy();
		ProxyManager.train = new TrainProxy();
		ProxyManager.arena = new ArenaProxy();
		ProxyManager.cultivate = new CultivateProxy();
		ProxyManager.uniqueSkill = new UniqueSkillProxy();
		ProxyManager.recharge = new RechargeProxy();
		ProxyManager.lottery = new LotteryProxy();
		ProxyManager.activity = new ActivityProxy();
		ProxyManager.welfare2 = new Welfare2Proxy();
		ProxyManager.timeLimitTask = new TimeLimitTaskProxy();
		ProxyManager.fashionPlayer = new FashionPlayerProxy();
		ProxyManager.gamePlay = new GamePlayProxy();
		ProxyManager.sevenDayMagicWeapon = new SevenDayMagicWeaponProxy();
		ProxyManager.friend = new FriendProxy();
		ProxyManager.guildBattle = new GuildBattleProxy();
		ProxyManager.cross = new CrossProxy();
		ProxyManager.magicweaponstrengthen = new MagicWeaponStrengthenProxy();
		ProxyManager.shape = new ShapeProxy();
		ProxyManager.peak = new PeakProxy();
		ProxyManager.certification = new CertificationProxy();
		ProxyManager.team2 = new Team2Proxy();
		ProxyManager.exam = new ExamProxy();
		ProxyManager.beastBattle = new BeastBattleProxy();
		ProxyManager.contest = new ContestProxy();
		ProxyManager.qualifying = new QualifyingProxy();
	}

	public static initCreateRole(): void {
		ProxyManager.createRole = new CreateRoleProxy();
	}
}