enum EPriceUnit {
	EPriceUnitCoinBind = 1, //银两
	EPriceUnitGold = 2,     //元宝
	EPriceUnitGoldBind = 3, //绑元
	EPriceUnitHonour = 4,   //荣誉
	EPriceUnitArena = 5,    //竞技场金券
	EPriceUnitPrestige = 6, //声望
	EPriceUnitPoint = 7,      //礼券
	EPriceUnitCopyScore = 8,//副本积分
	EPriceUnitGuildContribution = 9, //仙盟贡献
	EPriceUnitNimbus = 10,  // 灵气
	EPriceUnitAccumulation = 11,  // 聚气
	EPriceUnitInterHonour = 12,    // 跨服荣誉
	EPriceUnitWuxingEnergyValue = 13, //五行能量值
	EPriceUnitNewEnergy = 14,    //新精力值
	EPriceUnitPetCoin = 15,    //珍兽币
	EPriceUnitMagicStone = 16,    //魔石（远古竞技场）
	EPriceUnitMerit = 17,        //功勋（远古竞技场）
	EPriceUnitBrokenSoul = 18,  //破碎元神(猎命)
	EPriceUnitIntegralOne = 19, //龙宫币
	EPriceUnitIntegralTwo = 20, //天宫币
	EPriceUnitStarFortune = 21, //星运碎片
	EPriceUnitCopyEnergy = 22,  //副本体力值
	EPriceUnitMythScore = 23,    //封神积分
	EPriceUnitPurpleFortune = 24,    //紫色命力
	EPriceUnitGoldFortune = 25,    //金色命力
	EPriceUnitOrangeFortune = 26,    //橙色命力
	EPriceUnitAdvantageIntimate = 27,   //仙缘值
	EPriceUnitActivityValue = 28,     //--修真活跃值
	EPriceUnitCountryContribution = 29, //国家贡献
	EPriceUnitGuild = 30, //仙盟资金
	EPriceUnitReiki = 31,  //坐骑境界灵气值
	EPriceUnitWarehouseCredit = 32, //仙盟仓库积分
	EPriceUnitLotteryScore = 33,	//宝藏寻宝积分（抽箱子）
	EPriceUnitRuneExp = 34,   //符文经验
	EPriceUnitRuneCoin = 35,  //符文碎片
	EPriceUnitSoulExp = 36,   //灵魂经验
	EPriceUnitSoulStone = 37, //灵魂石
	EPriceUnitRuneCrystal = 38, //魔晶
	EPriceUnitDragonSpirit = 39, //龙魂值
	EPriceUnitHallowCivilization = 40,  // 诛仙强化石
	EPriceUnitHallowFighting = 41,      // 封神强化石
	EPriceUnitHallowRegulus = 42,       // 洪荒强化石
	EPriceUnitHallowAncient = 43,       // 混沌强化石
	EPriceUnitHallowEquip   = 44,       // 装备强化石
	EPriceUnitRoleExp = 44,					//修为
	EPriceUnitKillFragmentJunior = 45,		//初级必杀碎片精华
	EPriceUnitKillFragmentSenior = 46,		//高级必杀碎片精华
	EPriceUnitTrainScore = 47,		//历练
	EPriceUnitIllustratedExp = 48, // 图鉴经验
	EPriceUnitTalentExp = 49, // 天赋经验
    EPriceUnitJeton = 50, 		// 筹码
    EPriceUnitBeastEquipExp = 51,  // 神兽装备经验
	EPriceUnitFightingSpirit = 52,  // 斗魂货币

}