/**
 * 物品小类枚举
 */
enum EProp {
    EPropPackage = 1,                         //包裹
    EPropEquipStrengthenMaterial = 2,       //装备强化材料
    EPropEquipStrengthenLuckRune = 3,       //装备强化幸运符
    EPropEquipRefineMaterial = 4,              //装备精炼材料
    EPropEquipRefineLuckRune = 5,             //装备精练幸运符
    EPropEquipMakeHoleRune = 6,               //装备开孔符
    EPropEquipEmbedRune = 7,                //装备镶嵌符
    EPropEquipRemoveRune = 8,               //装备摘除符
    EPropJewelComposeRune = 9,                //宝石合成保护符
    EPropEquipRecastMaterial = 10,          //装备重铸材料
    EPropFixGiftBag = 11,                    //固定礼包
    EPropRandGiftBag = 12,                    //随机礼包
    EPropTrumpet = 13,                        //大喇叭
    EPropPassToCity = 14,                    //回城卷
    EPropPriceUnitCard = 15,                //货币卡
    EPropPassToTarget = 16,                    //传送（小飞鞋、飞天符、传送道具）
    EPropSkillBook = 17,                    //技能书
    EPropPetEgg = 18,                        //宠物蛋
    EPropPetGrowUpMaterial = 19,            //宠物成长提升道具
    EPropPetTalentAdvanceMaterial = 20,        //宠物灵性提升材料
    EPropPetTalentAdvanceRune = 21,            //宠物灵性提升幸运符
    EPropPetBreedMaterial = 22,                //宠物繁殖消耗材料
    EPropTaskLoopBook = 23,                    //循环任务书
    EPropColorStone = 24,                    //五彩石
    EPropPetGrowUpRune = 25,                //宠物成长提升幸运符
    EPropPassToCampCity = 26,                //阵营回城卷
    EPropTransportFlushToken = 27,            //换车令
    EPropOfflineAddExperience = 28,            //离线经验加倍药
    EPropPetCage = 29,                     //宠物笼
    EPropAiderBoss = 30,                    //帮手怪
    EPropSundries = 31,                        //杂货
    EPropGuildSpaceItem = 32,            // 购买仙盟领地道具
    EPropBox = 33,                        //箱子(开箱子系统)
    EPropHuntMap = 34,                    // 藏宝图
    EPropHuntShovel = 35,                //铲子
    EPropGuildCreat = 36,                // 建盟令（创建仙盟）
    EPropEquipStrengthenProp = 37,       //装备强化材料
    EPropEquipRefineProp = 38,              //装备精炼材料
    EPropTaskSilverNote = 39,            //任务银票（跑商任务相关道具）
    EPropGuildSilverNote = 40,            //仙盟银票（跑商过程中，被杀，掉落的银票，不纳入任务银票）
    EPropRunBusinessItem = 41,            //跑商商品（只有跑商商品，能放入跑商背包）
    EPropVIPCard = 42,              //VIP卡
    EPropFlower = 43,                //鲜花
    EPropLingBao = 45,            //百年玄铁
    EPropXuanTie = 46,            //改类型，被废弃
    EPropLingBaoDaemon = 47,    //百年玄铁保护符
    EPropDecompose = 48,        //分解符
    EPropRefresh = 49,            //洗炼石
    EPropGuildStructureProp = 50,   // 仙石  （加速仙盟建筑升级）
    EPropGuildAddResource = 51,     // 灵石  （加仙盟资源）
    EPropRevival = 52,            //复活道具
    EPropPetGrowUpProtect = 53,           // 宠物成长提升保护符
    EPropPetTalentAdvanceProtect = 54,    // 宠物灵性提升保护符
    EPropPetModelChange = 55,             // 宠物化形道具
    EPropPetSkillForget = 56,             // 宠物技能遗忘道具
    EPropPetSkillRand = 57,               // 宠物技能书随机获取道具
    EPropPetSkillDig = 58,                // 宠物技能提取道具
    EPropRootProp = 59,             // 根骨提升符
    EPropRootProtect = 60,          // 根骨保护符
    EPropFireWood = 61,                      // 柴火（仙盟圣火用）
    EPropNimbusBottle = 62,         // 灵气瓶
    EPropFishhook = 63,             //鱼钩
    EPropJewelChip = 64,        //宝石碎片
    EPropKillEvilToken = 65,    //诛邪令
    EPropFish = 66,                //鱼（活鱼）
    EPropUnbakedFish = 67,        //未熟鱼（半生熟）
    EPropCookedFish = 68,        //熟鱼
    EPropSkillPetBook = 69,        //宠物技能书
    EPropEquipStrengthenPerfectProp = 70,    //装备完美强化符
    EPropUseSkill = 71,            // 触发技能的道具
    EPropCopyBox = 72,            //副本箱子
    EPropHappyBag = 73,            //开心口袋
    EPropUpgradePrefix = 74,    //月之精华(提升装备品质)
    EPropSoap = 75,              //香皂（温泉互动使用道具）
    EPropSchoolToken = 76,        //宗门令
    EPropPetBlessAdd = 77,        //宠物祝福丹
    EPropPetXisui = 78,            //宠物洗髓道具
    EPropRefreshLock = 79,        //洗炼锁
    EPropLotteryKey = 80,        //仙境钥匙
    EPropEquipAdvanceExtend = 81,//装备进阶扩展道具
    EPropChristmasCard = 82,    //圣诞贺卡
    EPropPlayerRename = 83,        //玩家改名道具
    EPropGuildRename = 84,        //仙盟改名道具
    EPropArenaGiftBag = 85,        //竞技场礼包
    EPropFirework = 86,            //烟花
    EPropMelt = 87,                //熔炼符
    EPropInvitation = 88,        //请帖
    EPropTitle = 89,            //称号道具
    EPropPetTalent = 90,        //宠物资质道具
    EPropSuitSkillUpgrade = 91,    //提升套装技能相位等级道具
    EPropSuitSkillLock = 92,    //激活套装技能道具
    EPropChangeSex = 93,        //变性道具
    EPropWeddingFireWork = 94,    //婚礼烟花
    EPropWeddingBubble = 95,    //婚礼气球
    EPropWeddingCandy = 96,        //喜糖
    EPropWeddingPayBackCard = 97,    //婚礼补偿卡
    EPropPetInnerAlchemy = 98,    //灵兽内丹
    EPropPetEquipRecast = 99,    //宠物装备重铸材料
    EPropTreasureOre = 100,        //国家宝藏矿石
    EPropTreasureCrystal = 101,    //国家宝藏水晶
    EPropQuickCompleteTask = 102,    //快速完成任务道具
    EPropGuildLeaderImpeach = 103,    //盟主弹劾令
    EPropPrefixHolySpecial = 104,    //太阳精华（品质提升为神圣时的特殊材料）
    EPropGuildPartyHot = 105,    //仙盟宴会气氛值道具
    EPropMountAdvance = 106,    //坐骑进阶道具
    EPropMountAdvancePerfect = 107,        //坐骑进阶完美保护符
    EPropMountRefreshGrow = 108,        //坐骑洗髓丹
    EPropNewArenaGiftBag = 109,        //新竞技场礼包
    EPropFly = 110,                //飞行道具
    EPropJewelAdvance = 111,    //宝石打磨道具
    EPropGuildBeastFood = 112,    //仙盟boss口粮
    EPropGuildCallTogether = 113,//仙盟召集令
    EPropWuXingAttributeRefresh = 114,    //五行属性洗练道具
    EPropWuXingSpiritExp = 115,            //五行精魄经验道具
    EPropWuXingSpiritUpgrade = 116,        //五行精魄进阶道具
    EPropRuneGrowth = 117,        //符文成长道具
    EPropPetEquipPrefix = 118,    //宠物装备品质提升道具
    EPropSuperExp = 119, //超级经验丹
    EPropMagicPearl = 120,        //定水珠
    EPropGuildSkillLearn = 121,        //仙盟技能学习道具
    EPropMakeCakeMaterial = 122,    //蛋糕材料
    EPropFixStoneMaterial = 123,    //修石碑材料
    EPropCoinBind = 124,        //绑定铜钱
    EPropWuxingEnergy = 125,        //五行能量道具
    EPropRuneExtraNum = 126,        //符文开孔道具
    EPropMagicPearlEx = 127,        //避水珠
    EPropPetEquipTransform = 128,    //宠物装备转换道具
    EPropPetEquipRefresh = 129,        //宠物装备洗炼道具
    EPropChangeAvatar = 130,        //易容丹（更换头像）
    EPropMedal = 131,                //勋章
    EPropRootBreakThrough = 132,    //根骨突破丹
    EPropAchievementPoint = 133,    //增加成就点
    EProp5FBChip = 134,                //5FB币碎片
    EPropLifeStyleHunt = 135,       //猎命道具
    EPropMountReincarnate = 136,    //坐骑转生道具
    EPropAttribute = 137,            //属性道具
    EPropRandItemPetSkill = 138,    //如意宠物技能
    EPropRandItemJewel = 139,        //如意宝石
    EPropFarmSeed = 140,            //仙园种子
    EProPEquipStrengthenLuck = 141,    //装备强化幸运石
    EPropPetGrowthExperience = 142,    //宠物成长经验
    EPropPetSpiritExperience = 143, //宠物灵性经验
    EPropTowerCopySpiritStone = 144, //灵石
    EPropTowerCopyDoubleDrop = 145,     //万妖令（双倍掉落）
    EPropTreasureKey = 146,            //日常宝箱钥匙
    EPropFoundation = 147,            //凡人基金
    EPropSpecialMountCard = 148,        //特殊坐骑卡
    EPropWingIlluionReel = 149,            //时装翅膀幻化卡
    EPropFashionUpgrade = 150,            //时装精魄
    EPropFashionChip = 151,                    //时装碎片
    EPropFashionIllusionReel = 152,    //时装衣服幻化卡
    EPropFashionWeaponIllusionReel = 153, //时装武器幻化卡
    EPropSoulCrystal = 154, // --灵魂水晶
    EPropMountUpgradeAddition = 155, // -- 坐骑辅助
    EPropMoneyTreeAddition = 156, // -- 摇钱树辅助
    EPropFashionTrackIllusionReel = 157, //-- 时装足迹幻化卡
    EPropFashionHaloIllusionReel = 158, //-- 时装气息幻化卡
    EPropBless = 159, //祝福(经验)
    EPropCopyEnergy = 160,    //增加副本体力
    EPropFestivalClock = 161,    //新年钟声（银两）
    EPropGodCrystal = 162,    //神之水晶
    EPropStone = 163,    //凝血晶石
    EPropBlood = 164,    //血脉精魄
    EPropFiveElementDrug = 165,   // -- 五行丹
    EPropGatherSoulDrug = 166,    // -- 聚魂丹
    EPropSweetFruit = 167,      // 甜蜜果
    EPropNeidan = 168,              //坐骑晶核 （永久性）
    EPropCountryContrStatic = 169,    //国贡国库静态道具
    EPropCountryContrDynamic = 170,   //国贡国库动态道具
    EPropNimbusTreeAddition = 171,    //拜仙元气祈福辅助
    EPropLotterySeabedKey = 172,    //海底仙境钥匙
    EPropLotteryFloodKey = 173,        //洪荒仙境钥匙
    EPropGuildResource = 174,        //仙盟贡献
    EPropDiscountCard = 175,        //打折卡
    EPropPurifyFashion = 176,        //时装精炼道具
    EPropUpgradeLevelDrug = 177,    //提升等级的经验药
    EPropLoveZazenItem = 178,        //情缘区修炼物品
    EPropNeidanTimeLimit = 179,  //坐骑晶核 （时效性）
    EPropCrossTrumpet = 180,        //跨服喇叭物品
    EPropPetAwakedDrug = 181,        //宠物觉醒丹
    EPropItemOutOfTime = 182,  //过期类型物品
    EPropPetAwakedTimeLimitDrug = 183,  //宠物觉醒丹（时效性）
    EPropMagicWareTemplate = 184,   //法宝模版
    EPropMagicWareTip = 185,         //法宝之灵
    EPropPetIllusionUpgrade = 186,  //宠物幻化升级
    EPropChest = 187,               //宝箱
    EpropChestKey = 188,            //宝箱钥匙
    EPropCrossTreasureMap = 189,    //跨服挖宝宝图
    EPropEverAttr = 190,            //永久属性物品
    EPropMountEquipActive = 191,    //圣兽石
    EPropMountEquipUpgrade = 192,   //兽魂石
    EPropMountEquipstar = 193,      //兽魂珠
    EPropMountEquip = 194,          //兽魂珠
    EPropForShow = 195,             //展示
    EPropFashion = 196,             //时装道具
    EPropAddCopyNum = 197,          //增加副本次数
    EPropOfflineWork = 198,         //增加离线挂机时间
    EPropCopyEnter = 199,           //副本门票
    EPropAddBagCapacity = 200,      //扩展背包格子
    EPropUpgradeRealmLevel = 201,   //境界提升道具
    EPropDecreaseKillValue = 202,   //减少红名pk值道具
    EPropSmeltMaterial = 203,       //合成材料
    EPropRuneBox = 204,             //符文宝箱（温志华）
    EPropGoldBuyGiftBag = 205,      //消费宝箱
    EPropLottery = 206,             //宝藏钥匙
    EPropGuildBeastGodFood = 207,   //兽粮--兽神捐献
    EPropTire = 208,                //疲劳值
    EPropDestinyAwake = 209,        //命格碎片(天命觉醒)
    EPropNaturalGiftReset = 210,    //天赋重置
    EPropModifyRoleName = 211,      //角色改名卡
    EPropModifyGuildName = 212,     //仙盟改名卡
    EPropBegRune = 213,				//求符令
    EPropDelegateScroll = 214,      //扫荡卷轴
    EPropJewelRefineAttack = 215,   //攻击类宝石精炼道具
    EPropJewelRefineDefense = 216,  //防御类宝石精炼道具
    EPropBeastAddMaxBeckonNum = 217,//增加神兽助战上限
    EPropEquipUpgrade = 218,        //装备进阶道具
    EPropLotteryBox = 219,          //lottery箱子道具
    EPropPinkEquipSmeltSton = 220,  //神装合成道具
    EPropMarryApplyGift = 221,      //求婚彩礼
    EPropChildren = 222,            //仙娃激活道具
    EPropGuildRedPacket = 223,      //仙盟红包道具
    EPropShapeChangeEx = 224,       //骑宠皮肤激活道具
    EPropChangeBaseCareer = 225,    //职业转换卡
    EPropDragonAwake = 226,         //碎片(龙神觉醒)
    EPropMagpieFeather = 227,       //鹊羽
    EPropGold = 228,        		//元宝
    EPropRoleState = 229,        	//转生丹
    EPropRoleExp = 230,				//降级（换取修为）
    EPropGodEquipfragment = 231,    //神装碎片
    EPropKillFragment = 232,			//必杀碎片精华
    EPropUpgradeLevel = 233,        //等级直升丹
    EPropUpgradeWing = 234,        //翅膀直升丹
    EPropPriceUnitCardNew = 235,       //新货币卡（获得时自动使用）
    EPropRechargeCard = 236,            //充值卡
    EPropGuildFixGiftBag = 237,                    //仙盟固定礼包（加入仙盟后才能使用）
    EPropStrengthenExAccessory = 238,       //新强化系统附属物
    EPropStrengthenExAccessoryFragment = 239,       //新强化系统附属物碎片
    EPropIllustratedExp = 240,       //图鉴经验卡
    EPropIllustratedCard = 241,       //图鉴卡片
    EPropImmortals = 242,       //神兵
    EPropImmortalsFragment = 243,       //神兵碎片
    EPropWarmBloodFragment = 244,       //热血碎片
	EPropForeverEquipProp = 245,       //传世道具
    EPropForeverJewelStone = 246,       //传世宝钻
    EPropRechargeGiftBag = 247,   //超值大礼包
    EPropShapeEquip = 248,       //外形装备
    EPropCittaFragment  = 249,   //心法碎片
	EPropChoseGiftBag = 250,     //自选礼包
    EPropQiongCangToken = 251,       //穹苍令
    EPropRuneMine = 252,       //符文矿脉
    EPropActivedGiftBag = 253, //激活码礼包
    EPropShapeAdvance = 254,   //外形直升一阶
	EPropLawExp = 255, //法阵经验卡
    EPropLawSkillBook = 256, //法阵技能升级书	
	EPropUpgradeStrengthenEx  = 257,        //强化直升丹
    EPropShapeChangeActive = 258, //法宝外形激活
    EPropShapeAdvanceEx  = 259,        		//外形进阶丹(只能在某阶使用)
	EPropUpgradeStrengthenEx2  = 260,       //强化化直升丹(只能在某阶使用)
    EPropPeakArena  = 261,        //巅峰令
    EPropVipLimitedGiftBag = 262, //VIP特惠礼包
    EPropCheckpointRoleExp = 263,        //关卡领取修为
    EPropBeastEquipStone = 264,      //神兽装备合成材料
    EPropGuildWareHouse = 265,      //仙盟仓库捐献道具
    EPropWingShow = 266,  //展示道具，客户端有拾取动作，服务端不进背包
    EPropContest  = 268,        //守擂令牌
    EPropLevelGiftBag = 269,    //等级礼包（effect对应礼包code  effect_ex 对应开启的等级 effect_ex2对应开启的转生）
    EPropStateLevelGiftBagHand = 270,      //手动使用的奖励转生和等级礼包道具（effect 字段对应 t_copy_reward_state_level_gift_bag 中的 code , 手动使用）
    EPropDynamicRoleStateProp = 271,      //动态转生丹（根据转生等级获得修为）
    EPropBossExtraDropActiveGiftBag = 272,      //Boss献礼活动宝箱（effect 对应随机礼包 code，effect_ex 超时使用对应的随机礼包 code）
    EPropTempRechargeCard = 273,//体验卡 effect填充值卡类型 effect_ex填时间 秒
}