/**
 * 资源包名
 */
class PackNameEnum {
	//------开头这段专门放特效的包-------
	public static MCStartGame1: string = "MCStartGame1";//开始游戏
	public static MCStartGame2: string = "MCStartGame2";//开始征程
	public static MCCheckPoint: string = "MCCheckPoint";//关卡空进度特效
	public static MCCheckPointFull: string = "MCCheckPointFull"; //关卡满进度特效
	public static MCCheckPointFire: string = "MCCheckPointFire";//关卡火焰特效
	public static MCClick: string = "MCClick"; //指引点击特效
	public static MCClickForce: string = "MCClickForce"; //强制指引点击特效
	public static MCExpAdd: string = "MCExpAdd"; //经验增加的特效
	public static MCExpAdd2: string = "MCExpAdd2"; //经验增加的特效
	public static MCExpBao: string = "MCExpBao"; //经验增加的爆点特效
	public static MCFightAdd: string = "MCFightAdd"; //增加战力的特效
	public static MCFightFire: string = "MCFightFire"; //通用战力面板的特效
	public static MCGodEqui: string = "MCGodEqui"; //baseItem神装特效
	public static MCOneKey: string = "MCOneKey"; //一键换装的特效 通用按钮特效
	public static MCTrain: string = "MCTrain"; //爵位界面 历练奖励图标特效
	public static MCKingBattleUpgrade: string = "MCKingBattleUpgrade";//王者争霸段位提升
	public static MCStar: string = "MCStar";//星星特效
	public static MCReincarnation: string = "MCReincarnation";//转生特效
	public static MCReinSuccess: string = "MCReinSuccess";//转生成功
	public static MCHomeIcon: string = "MCHomeIcon";//图标光效
	public static MCRecharge: string = "MCRecharge";//首充按钮特效
	public static MCLock: string = "MCLock";//诛仙塔锁
	public static MCTower: string = "MCTower";//诛仙塔挑战提醒
	public static MCRefineProgress: string = "MCRefineProgress";//精炼进度
	public static MCRefineProgressFull: string = "MCRefineProgressFull";//精炼满进度
	public static MCActivation: string = "MCActivation";//激活成功
	public static MCLight: string = "MCLight";//光效	
	public static MCFinger: string = "MCFinger";//手指点击
	public static MCTaskGet: string = "MCTaskGet";//领取任务
	public static MCTaskEnd: string = "MCTaskEnd";//结束任务
	public static MCTaskComplete: string = "MCTaskComplete";//完成任务流光
	public static MCTaskUnComplete: string = "MCTaskUnComplete";//任务未完成扫光
	public static MCEquipBest: string = "MCEquipBest";//流光
	public static MCLotteryTitleTxt: string = "MCLotteryTitleTxt";//寻宝特效标题
	public static MCInnerPowerBig: string = "MCInnerPowerBig";//内功大爆炸特效标题
	public static MCInnerPowerSmall: string = "MCInnerPowerSmall";//内功小爆炸特效标题
	public static MCInnerPowerFly: string = "MCInnerPowerFly";//内功飞行轨迹特效标题
	public static MCInnerPowerBall: string = "MCInnerPowerBall";//内功球特效资源包
	public static MCInnerPowerBallTop: string = "MCInnerPowerBallTop";//内功球特效资源包
	public static MCInnerPowerBurn: string = "MCInnerPowerBurn";//内功燃烧特效资源包
	public static NumCheckPoint: string = "NumCheckPoint";//关卡字体
	public static MCGoto: string = "MCGoto";//前往 文字链接按钮
	public static MCBaGuaPai: string = "MCBaGuaPai";//显示任务的八卦牌特效
	public static MCReturn: string = "MCReturn";//导航栏返回按钮特效
	public static MCUniqueSkill: string = "MCUniqueSkill";//必杀碎片特效
	public static MCItemColor3: string = "MCItemColor3";//颜色是3的物品特效
	public static MCItemColor4: string = "MCItemColor4";//颜色是4的物品特效
	public static MCItemColor5: string = "MCItemColor5";//颜色是5的物品特效
	public static MCItemColor6: string = "MCItemColor6";//颜色是6的物品特效
	public static MCBreak: string = "MCBreak";//神兵突破
	public static MCCheatSuccee: string = "MCCheatSuccee";//秘籍镶嵌成功
	public static MCCheckPointTxt:string = "MCCheckPointTxt";//关卡挑战提示文字流光特效
	public static MCCheckPointTxt2:string = "MCCheckPointTxt2";//关卡挑战提示"关卡"文字特效
	public static MCCircle:string = "MCCircle";//圆形特效，Z职业框特效
	public static MCBomb:string = "MCBomb";//天赋合成成功特效
	public static MCRCFWeapon:string = "MCRCFWeapon";//首充武器特效
	public static MCRCFCircle:string = "MCRCFCircle";//首充转圈
	public static MCRCFIcoWeapon:string = "MCRCFIcoWeapon";//首充转圈
	public static MCRechargeFirstIco:string = "MCRechargeFirstIco";//首充图标
	public static MCBossComing:string = "MCBossComing";//boss来袭进度特效
	public static MCHideBoss:string = "MCHideBoss";//隐藏boss特效
	public static MCBossComingFull:string = "MCBossComingFull";//boss来袭击杀进度满特效
	public static MCRechargeLight:string = "MCRechargeLight";//首充底光
	public static MCGuideClick:string = "MCGuideClick";//新指引特效
	public static MCLotteryResultTitle:string = "MCLotteryResultTitle";//寻宝获得奖励标题特效
	public static MCHJOpen:string = "MCHJOpen";//必杀技开启
	public static MCCommonButton:string = "MCCommonButton";//通用按钮特效
	public static MCExpBar:string = "MCExpBar";//经验条
	public static MCRedPoint:string = "MCRedPoint";//红点
	public static MCBroadRound:string = "MCBroadRound";//
	
	public static StartStory: string = "StartStory";
	public static BlueSkin: string = "BlueSkin";
	public static Sound: string = "Sound";
	public static Loading: string = "Loading";
	public static Login: string = "Login";
	public static CreateRole: string = "CreateRole";
	public static MCLifeBall: string = "MCLifeBall";//血球
	public static MCHeji: string = "MCHeji";//合击特效
	public static MCHejiPoint: string = "MCHejiPoint";//合击特效光点
	public static MCHejiOk: string = "MCHejiOk";//合击满特效
	public static GetNewSkill: string = "GetNewSkill";//获取新技能
	public static Common: string = "Common";
	public static Num: string = "Num";//公共图片文字
	public static Navbar: string = "Navbar";
	public static Home: string = "Home";
	public static HomeIcon: string = "HomeIcon";
	public static HomeChat: string = "HomeChat";
	public static BattlePanel: string = "BattlePanel";
	public static Pack: string = "Pack";
	public static Player: string = "Player";
	public static PlayerOther: string = "PlayerOther";
	public static Reincarnation: string = "Reincarnation";
	public static Resurgence: string = "Resurgence";//复活
	public static MsgBroadcast: string = "MsgBroadcast";//消息广播
	public static Skill: string = "Skill";//技能系统
	public static Task: string = "Task";//任务
	public static Train: string = "Train";//历练
	public static TrainGW1: string = "TrainGW1";//历练->神器碎片合成
	public static TrainGodWeaponPanel: string = "TrainGodWeaponPanel";//历练->神器主界面
	public static TrainNobilityPanel: string = "TrainNobilityPanel";//历练->爵位主界面
	public static TrainMedalPanel: string = "TrainMedalPanel";//历练->勋章主界面
	public static TrainIllustratePanel: string = "TrainIllustratePanel";//历练->图鉴主界面
	public static Activation: string = "Activation";//激活提示界面
	public static TaskDialog: string = "TaskDialog";//任务对话
	public static Copy: string = "Copy";//副本
	public static CopyResult: string = "CopyResult";//副本结算包
	public static Copy2: string = "Copy2";//副本分包
	public static CopyAssit: string = "CopyAssit";//副本协助
	public static CopyHall: string = "CopyHall";//副本大厅
	public static CopyDaily: string = "CopyDaily";//日常副本
	public static CopyTower: string = "CopyTower";//诛仙塔
	public static CopyLengend: string = "CopyLegend";//传奇之路
	public static TowerTurntable: string = "TowerTurntable";//诛仙塔抽奖
	public static Scene: string = "Scene"//场景;
	public static SceneBossInfo: string = "SceneBossInfo"//场景boss头像;
	public static Fashion: string = "DressUp";//时装
	public static FashionII: string = "FashionII";//新版时装
	public static FashionTitle: string = "FashionTitle";//时装称号
	public static FashionPlayer: string = "FashionPlayer";//时装角色等
	public static WorldMap: string = "WorldMap";//世界地图
	public static MovieClip: string = "MovieClip";//特效-已弃用
	public static MCItemExplode: string = "MCItemExplode";//
	public static MCMelting: string = "MCMelting";//熔炼
	public static MCStrengthen: string = "MCStrengthen";//
	public static MCSuccessAdd: string = "MCSuccessAdd";//
	public static MCProgressBarPoint: string = "MCProgressBarPoint";//进度条光点
	public static MCRcgBtn: string = "MCRcgBtn";//首充按钮特效
	public static MCRcgBtn2: string = "MCRcgBtn2";//首充按钮特效2
	public static MCStage: string = "MCStage";//外观开启舞台特效
	public static MCActivityRankIcon: string = "MCActivityRankIcon";//冲榜排名图标特效
	public static MCLaba : string = "MCLaba";
	

	public static WorldBoss: string = "WorldBoss";//世界boss
	public static Shop: string = "Shop";//商城
	public static Refine: string = "Refine";//炼器
	public static Guild: string = "Guild";//仙盟
	public static GuildNew: string = "GuildNew";//仙盟
	public static GodWing: string = "GodWing";//神羽
	public static GodWingEquipPanel: string = "GodWingEquipPanel";//神羽-装备
	public static GodWingPanel: string = "GodWingPanel";//神羽-转换/合成
	public static GuildNewBasics: string = "GuildNewBasics";//仙盟 基础面板
	public static GuildNewCreate: string = "GuildNewCreate";//仙盟 创建和申请
	public static GuildNewMember: string = "GuildNewMember";//仙盟 成员
	public static GuildNewManager: string = "GuildNewManager";//仙盟 管理
    public static GuildHome: string = "GuildHome";//仙盟主界面
	public static GuildCopy:string = "GuildCopy";//仙盟副本
	public static Test: string = "Test";//Test
	public static Rune: string = "Rune";//符文
	public static RuneShop: string = "RuneShop";//符文兑换商店
	public static Chat: string = "Chat";//聊天
	public static ChatFace: string = "ChatFace";//聊天
	public static ChatFaceView: string = "ChatFaceView";//聊天
	public static Friend: string = "Friend";//好友
	public static Mail: string = "Mail";//邮件
	public static Welcome: string = "Welcome";//欢迎
	public static Setup: string = "Setup";//设置
	public static VIP: string = "VIP";//VIP
	public static ReceiveItemTips: string = "ReceiveItemTips";//获取物品飘提示
	public static Team: string = "Team";//组队
	public static Open: string = "Open";//功能开启
	public static GuildePanel: string = "GuildePanel";
	public static OpenPanel: string = "OpenPanel";
	public static ChangeCareer: string = "ChangeCareer";//转职
	public static Compose: string = "Compose";//合成
	public static Achievement: string = "Achievement";//成就
	public static Daily: string = "Daily";
	public static Guide: string = "Guide";
	public static Title: string = "Title";//称号
	public static Realm: string = "Realm";//境界
	public static Recharge: string = "Recharge";//充值
	public static MagicWeaponCopy: string = "MagicWeaponCopy";//法宝副本
	public static RechargeFirst: string = "RechargeFirst";//境界
	public static Welfare: string = "Welfare";//福利
	public static Rank: string = "Rank";//排行榜
	public static RankRush: string = "RankRush";//开服冲榜
	public static OpenRole: string = "OpenRole";//开角色
	public static SevenDays: string = "SevenDays";//七天登录
	public static BibleActivity: string = "BibleActivity";//天书寻主
	public static Boss: string = "Boss";//Boss
	public static BossHome:string = "BossHome";
	public static Forge: string = "Forge";//锻造
	public static ForgeStrengthen: string = "ForgeStrengthen";//强化
	public static ForgeCasting: string = "ForgeCasting";//铸造
	public static ForgeRefine: string = "ForgeRefine";//精炼
	public static ForgeImmortals: string = "ForgeImmortals";//神兵
	public static GodEquip: string = "GodEquip";//神装
	public static Shura: string = "Shura";//修罗
	public static MagicWare: string = "MagicWare";//法器
	public static Arena: string = "Arena";//竞技
	public static MicroClient: string = "MicroClient";//微端下载奖励
	public static FollowReward: string = "FollowReward";//关注奖励
	public static PropGet: string = "PropGet";//道具获取
	public static UniqueSkill: string = "UniqueSkill";//必杀
	public static Lottery: string = "Lottery";//寻宝
	public static LotteryAsset: string = "LotteryAsset";//寻宝特效资源包
	public static InnerPower: string = "InnerPower";//内功
	public static SkillCheats: string = "SkillCheats";//秘籍
	public static Activity: string = "Activity";//活动
	public static ActivityII: string = "ActivityII";//活动分包资源
	public static ActivityIII: string = "ActivityIII";//活动分包资源
	public static ActivityIV: string = "ActivityIV";
	public static ActivityShop: string = "ActivityShop";//商店购买类活动分包
	public static ActivityBoss: string = "ActivityBoss";//全民boss活动
	public static ActivityBoss2: string = "ActivityBoss2";//全民boss活动独立界面
	public static ActivityScore: string = "ActivityScore";//积分兑换
	public static ActivityRank: string = "ActivityRank";//冲榜活动
	public static ActivityWar:string = "ActivityWar";//战场类玩法-开服活动做显示入口
	public static ActGroupBuy:string = "ActGroupBuy";//首充团购
	public static ActivityInvest:string = "ActivityInvest";//投资计划
	public static ActivityLimitRecharge:string = "ActivityLimitRecharge";//限时充值
	public static VipGift: string = "VipGift";//VIP礼包
	public static AncientEquip: string = "AncientEquip";//传世装备	
	public static ActivityDayRecharge: string = "ActivityDayRecharge";//每日充值快速入口
	public static Welfare2: string = "Welfare2";//福利新版
	public static WelfareSignIn: string = "WelfareSignIn";//签到
	public static WelfareLoginReward: string = "WelfareLoginReward";//登陆奖励
	public static Welfare2GoldCard: string = "Welfare2GoldCard";//元宝月卡
	public static Welfare2PrivilegeCard: string = "Welfare2PrivilegeCard";//特权月卡
	public static Welfare2Cdkey: string = "Welfare2Cdkey";//激活码
	public static UpgradeGuide: string = "UpgradeGuide";//我要升级
	public static MCRoop: string = "MCRoop";//签到元宝特效
	public static MCSginReward: string = "MCSginReward";//签到奖励特效
	public static FightPlayers:string = "FightPlayers";//PVP战斗显示列表
	public static KingBattle:string = "KingBattle";//王者争霸
	public static Encounter:string = "Encounter";//遭遇战
	public static TimeLimitTask:string = "TimeLimitTask";//限时任务
	public static TimeLimitTaskOpen:string = "TimeLimitTaskOpen";//限时任务开启界面
	public static TimeLimitBoss:string = "TimeLimitBoss";//限时世界boss
	public static Mining:string = "Mining";//旷工
	public static MiningHire:string = "MiningHire";//雇佣矿工
    public static GuildActivity: string = "GuildActivity";//仙盟活动
    public static GuildVein: string = "GuildVein";//仙盟心法
    public static GuildBonfire: string = "GuildBonfire";//仙盟篝火
	public static GamePlay:string = "GamePlay";//玩法
	public static SevenDayMagicWeapon:string = "SevenDayMagicWeapon";//玩法
	public static GuildBattle:string = "GuildBattle";//仙盟争霸
	public static MagicWeaponStrengthen:string = "MagicWeaponStrengthen";
	public static Cross:string = "Cross";//跨服
	public static CrossBoss:string = "CrossBoss";//跨服BOSS
	public static CrossBossGuild:string = "CrossBossGuild";//跨服仙盟抢boss
	public static Pet:string = "Pet";//宠物
	public static PetChange: string = "PetChange";//宠物幻形
	public static Mount:string = "Mount";//坐骑
	public static MountChange: string = "MountChange";//坐骑幻形
	public static Vip3Reward:string = "Vip3Reward";//VIP3奖励引导
	public static ActivitySeven:string = "ActivitySeven";//七天狂欢
	public static RpgTeam:string = "RpgTeam";//场景队伍列表
	public static QiongCang:string = "QiongCang";//穹苍系统
	public static QiongCangBoss:string = "QiongCangBoss";//穹苍圣殿Boss系统
	public static QiongCangCopy:string = "QiongCangCopy";//穹苍圣殿爬塔副本
	public static QiongCangSmelt:string = "QiongCangSmelt";//圣物合成
	public static CopyStar:string = "CopyStar";//穹苍圣殿爬塔副本
	public static TalentCultivate:string = "TalentCultivate";//天赋培养系统
	public static OnlineReward:string = "OnlineReward";//在线奖励
    public static Peak:string = "Peak";//巅峰竞技
    public static PeakCD:string = "PeakCD";//巅峰竞技倒计时
    public static Team2:string = "Team2";//组队2
	public static MagicArray:string = "MagicArray";//法阵
	public static MagicArrayChange : string = "MagicArrayChange";//法阵幻化
	public static Shape : string = "Shape";//外形 公共组件
	public static MagicWeaponChange : string = "MagicWeaponChange";//法宝幻形
	public static ShapeBattle : string = "ShapeBattle";
	public static ShapeBattleChange : string = "ShapeBattleChange";
	public static BossComing:string = "BossComing";//Boss来袭
	public static SwordPool : string = "SwordPool";//剑池
	public static SwordPoolChange : string = "SwordPoolChange";//剑池幻形
	public static Exam : string = "Exam";//科举比赛
	public static MagicWingChange : string = "MagicWingChange";//翅膀幻形
	public static RechargeFirstIco:string = "RechargeFirstIco";//首充图标
	public static HomeActivityRank:string = "HomeActivityRank";//主界面冲榜排名图标
	public static Operating:string = "Operating";//运营礼包
	public static HideBoss:string = "HideBoss";//隐藏boss
	public static BeastBattle:string = "BeastBattle";//神兽助战
	public static MCIlltrainActive:string = "MCIlltrainActive";//图鉴可激活特效
    public static Contest:string = "Contest";//1VN
    public static Qualifying:string = "Qualifying";//3V3
    public static QualifyingResult:string = "QualifyingResult";//3V3
    public static CopyQualifying:string = "CopyQualifying";//3V3副本界面
	public static PrivilegeExpCard:string = "Welfare2PrivilegeExpCard";
	public static SpecialEquip:string = "SpecialEquip";//特殊装备
}